<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simple_car">
    <xacro:property name="wheel_mass" value="200"/>
    <xacro:property name="wheel_radius" value="0.505"/>
    <xacro:property name="wheel_length" value="0.4"/>
    <xacro:property name="body_mass" value="1580"/>
    <xacro:macro name="link_box" params="name mass length width height">
        <link name="${name}">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia ixx="${1/12*mass*(height**2 + width**2)}" ixy="0" ixz="0" 
                    iyy="${1/12*mass*(height**2 + length**2)}" iyz="0"
                    izz="${1/12*mass*(length**2 + width**2)}"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>
    <xacro:macro name="link_box_mesh" params="name mass length width height mesh_uri">
        <link name="${name}">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia ixx="${1/12*mass*(height**2 + width**2)}" ixy="0" ixz="0" 
                    iyy="${1/12*mass*(height**2 + length**2)}" iyz="0"
                    izz="${1/12*mass*(length**2 + width**2)}"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="${mesh_uri}"/> 
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>
    <xacro:macro name="wheel_macro" params="name parent mass radius length xyz">
        <link name="${name}_base">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="1"/>
                <inertia ixx="1" ixy="0" ixz="0" 
                    iyy="1" iyz="0"
                    izz="1"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0.075" rpy="0 0 0"/>
                <geometry>
                    <box size="0.3 0.3 0.15"/>
                </geometry>
            </visual>
        </link>
        <link name="${name}_steer">
            <inertial>
                <mass value="1"/>
                <inertia ixx="1" ixy="0" ixz="0" 
                    iyy="1" iyz="0"
                    izz="1"/>
            </inertial>
            <visual>
                <origin xyz="0 0 -0.075" rpy="0 0 0"/>
                <geometry>
                    <box size="0.3 0.3 0.15"/>
                </geometry>
            </visual>
        </link>
        <link name="${name}_tire">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia ixx="${1/12*mass*(3*radius**2 + length**2)}" ixy="0" ixz="0" 
                    iyy="${1/12*mass*(3*radius**2 + length**2)}" iyz="0"
                    izz="${1/2*mass*radius**2}"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
<!-- 
                    <cylinder radius="${radius}" length="${length}"/>
-->
                    <mesh filename="model://simple_car/resources/tire/tire.dae"/> 
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
            </collision>
        </link>
        <joint name="joint_${parent}_to_${name}_base" type="fixed">
            <origin xyz="${xyz}" rpy="0 0 0"/>
            <parent link="${parent}"/>
            <child link="${name}_base"/>
            <axis xyz="0 0 1"/>
            <limit lower="-1" upper="1" effort="10000000000000000" velocity="100"/>
            <safety_controller soft_lower_limit="0" soft_upper_limit="0" k_position="1" k_velocity="1"/>
        </joint>
        <joint name="joint_${name}_base_to_${name}_steer" type="continuous">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <parent link="${name}_base"/>
            <child link="${name}_steer"/>
            <axis xyz="0 0 1"/>
        </joint>
        <joint name="joint_${name}_steer_to_${name}_tire" type="continuous">
            <origin xyz="0 0 ${-radius - 0.15}" rpy="${-pi/2} 0 0"/>
            <parent link="${name}_steer"/>
            <child link="${name}_tire"/>
            <axis xyz="0 0 1"/>
        </joint>
        <!--
            <transmission name="${name}_steer_transmission">
                <type>transmission_interface/SimpleTransmission</type>
                <actuator name="$${name}_steer_motor">
                    <mechanicalReduction>1</mechanicalReduction>
                </actuator>
                <joint name="joint_${name}_base_to_${name}_steer">
                    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                </joint>
            </transmission>
        -->
        <gazebo reference="${name}_steer">
            <material>Gazebo/Blue</material>
        </gazebo>
        <!--
        <gazebo reference="${name}_tire">
            <material>Gazebo/Orange</material>
            <mu1>0.9</mu1>
            <mu2>0.8</mu2>
        </gazebo>
        -->
        <gazebo>
            <plugin name="${name}" filename="libwheel.so">
                <steer_joint name="joint_${name}_base_to_${name}_steer"/> 
                <drive_joint name="joint_${name}_steer_to_${name}_tire"/> 
            </plugin>
        </gazebo>
    </xacro:macro>

    <xacro:link_box name="base_link" mass="${body_mass}" length="1" width="1" height="1"/>
    <xacro:wheel_macro name="wheel_fl" parent="base_link" mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_length}" xyz="0.2 1 0"/>
    <xacro:wheel_macro name="wheel_rl" parent="base_link" mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_length}" xyz="-3 1 0"/>
    <xacro:wheel_macro name="wheel_rr" parent="base_link" mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_length}" xyz="-3 -1 0"/>
    <xacro:wheel_macro name="wheel_fr" parent="base_link" mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_length}" xyz="0.2 -1 0"/>

    <xacro:property name="tool_mass" value="400"/>
    <link name="tool_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${tool_mass}"/>
            <inertia ixx="${1/12*tool_mass*(1**2 + 4.5**2)}" ixy="0" ixz="0" 
                iyy="${1/12*tool_mass*(1**2 + 0.5**2)}" iyz="0"
                izz="${1/12*tool_mass*(0.5**2 + 4.5**2)}"/>
        </inertial>
        <visual>
            <origin xyz="0 0 -0.4" rpy="0 0 1.57"/>
            <geometry>
                <mesh filename="model://simple_car/resources/tool/tool.dae"/> 
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.7 5.5 1.2"/>
            </geometry>
        </collision>
    </link>
    <joint name="joint_tool_to_base_base" type="fixed">
        <origin xyz="-0.9 0 -0.2" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="tool_link"/>
        <axis xyz="0 0 1"/>
    </joint>
        
    <gazebo>
        <plugin name="vehicle" filename="libvehicle_body.so">
        </plugin>
    </gazebo>
</robot>
