std_msgs/Header header

float64 course
float64 course_reference
float64 course_error

float64 sideslip_reference
float64 sideslip

float64 speed
float64 speed_reference
float64 speed_command
float64 speed_error

float64 yaw
float64 yaw_reference
float64 yaw_error

float64 yawrate
float64 yawrate_reference
float64 yawrate_command
float64 yawrate_error

bool guidance_ready 
bool yaw_ready

geometry_msgs/Point icr
float64 curvature