/* Simulation code for Vehicle generated by the OpenModelica Compiler OpenModelica 1.13.0. */
#if !defined(Vehicle__MODEL_H)
#define Vehicle__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "Vehicle_functions.h"


extern void Vehicle_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Vehicle_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Vehicle_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Vehicle_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Vehicle_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Vehicle_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Vehicle_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Vehicle_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Vehicle_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Vehicle_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Vehicle_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Vehicle_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Vehicle_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* Vehicle_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Vehicle_relationDescription(int i);
extern void Vehicle_function_initSample(DATA *data, threadData_t *threadData);
extern int Vehicle_initialAnalyticJacobianG(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Vehicle_initialAnalyticJacobianA(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Vehicle_initialAnalyticJacobianB(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Vehicle_initialAnalyticJacobianC(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Vehicle_initialAnalyticJacobianD(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Vehicle_functionJacG_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Vehicle_functionJacA_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Vehicle_functionJacB_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Vehicle_functionJacC_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Vehicle_functionJacD_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* Vehicle_linear_model_frame(void);
extern const char* Vehicle_linear_model_datarecovery_frame(void);
extern int Vehicle_mayer(DATA* data, modelica_real** res, short *);
extern int Vehicle_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Vehicle_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Vehicle_setInputData(DATA *data, const modelica_boolean file);
extern int Vehicle_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Vehicle_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Vehicle_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int Vehicle_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void Vehicle_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void Vehicle_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Vehicle_inputNames(DATA* data, char ** names);
extern int Vehicle_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Vehicle_functionLocalKnownVars(DATA*, threadData_t*);
extern int Vehicle_symbolicInlineSystem(DATA*, threadData_t*);

#include "Vehicle_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(Vehicle__MODEL_H) */


