<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="vehicle">
  <!-- Body properties -->
  <xacro:property name="body_mass" value="2000.0"/>
  <xacro:property name="body_length" value="1.0"/>
  <xacro:property name="body_width" value="1.5"/>
  <xacro:property name="body_height" value="1.5"/>

  <!-- Wheel properties -->
  <xacro:property name="wheel_mass" value="200"/>
  <xacro:property name="wheel_radius" value="0.6"/>
  <xacro:property name="wheel_width" value="0.4"/>
  <xacro:property name="wheel_f_clear" value="0.1"/>
  <xacro:property name="wheel_r_x" value="-4"/>

  <!-- Beam properties -->
  <xacro:property name="beam_mass" value="200.0"/>
  <xacro:property name="beam_length" value="3.5"/>
  <xacro:property name="beam_width" value="0.3"/>
  <xacro:property name="beam_height" value="0.3"/>

  <!-- Macros -->
  <xacro:macro name="inertia_box" params="mass lx ly lz">
    <inertia
      ixx="${1/12*mass*(ly**2 + lz**2)}" 
      ixy="0" 
      ixz="0" 
      iyy="${1/12*mass*(lx**2 + lz**2)}" 
      iyz="0" 
      izz="${1/12*mass*(lx**2 + ly**2)}" 
    />
  </xacro:macro>
  <xacro:macro name="inertia_cylinder" params="mass r l">
    <inertia
      ixx="${(1/12)*mass*(3*r**2 + l**2)}" 
      ixy="0" 
      ixz="0" 
      iyy="${(1/12)*mass*(3*r**2 + l**2)}" 
      iyz="0" 
      izz="${(1/2)*mass*r**2}"
    />
  </xacro:macro>
  <xacro:macro name="material_tire">
    <material name="tire">
      <color rgba="0.2392 0.2157 0.1686 1"/>
    </material>
    <contact>
      <!-- ground plane has friction value of 1, so use 
        friction value for tire-groundtype that is found online. -->
      <lateral_friction value="0.8"/>
    </contact>
  </xacro:macro>


  <link name="body">
    <inertial>
      <mass value="${body_mass}"/>
      <xacro:inertia_box mass="${body_mass}" lx="${body_length}" ly="${body_width}" lz="${body_height}"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
  </link>
  <link name="beam_left">
    <inertial>
      <mass value="${beam_mass}"/>
      <xacro:inertia_box mass="${beam_mass}" lx="${beam_length}" ly="${beam_width}" lz="${beam_height}"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${beam_length} ${beam_width} ${beam_height}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${beam_length} ${beam_width} ${beam_height}"/>
      </geometry>
    </collision>
  </link>
  <link name="beam_right">
    <inertial>
      <mass value="${beam_mass}"/>
      <xacro:inertia_box mass="${beam_mass}" lx="${beam_length}" ly="${beam_width}" lz="${beam_height}"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${beam_length} ${beam_width} ${beam_height}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${beam_length} ${beam_width} ${beam_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="wheel_fl">
    <inertial>
      <mass value="${wheel_mass}"/>
      <xacro:inertia_cylinder mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_width}"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="-1.57 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="-1.57 0 0"/>
    </collision>
    <xacro:material_tire />
  </link>
  <link name="wheel_rl">
    <inertial>
      <mass value="${wheel_mass}"/>
      <xacro:inertia_cylinder mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_width}"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="-1.57 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="-1.57 0 0"/>
    </collision>
    <xacro:material_tire />
  </link>
  <link name="wheel_rr">
    <inertial>
      <mass value="${wheel_mass}"/>
      <xacro:inertia_cylinder mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_width}"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
    </collision>
    <xacro:material_tire />
  </link>
  <link name="wheel_fr">
    <inertial>
      <mass value="${wheel_mass}"/>
      <xacro:inertia_cylinder mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_width}"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
    </collision>
    <xacro:material_tire />
  </link>

  <!-- Beam joints -->
  <joint name="body_to_beam_left" type="fixed">
    <parent link="body"/>
    <child link="beam_left"/>
    <origin xyz="${body_length/2 - beam_length/2} ${body_width/2 - beam_width/2} ${body_height/2 + beam_height/2}"/>
  </joint>
  <joint name="body_to_beam_right" type="fixed">
    <parent link="body"/>
    <child link="beam_right"/>
    <origin xyz="${body_length/2 - beam_length/2} ${-body_width/2 + beam_width/2} ${body_height/2 + beam_height/2}"/>
  </joint>


  <joint name="body_to_wheel_fl" type="continuous">
    <parent link="body"/>
    <child link="wheel_fl"/>
    <origin xyz="0 ${body_width/2 + wheel_width/2 + wheel_f_clear} ${-body_height/2}"/>
    <axis xyz="0 1 0"/>
  </joint>
  <joint name="body_to_wheel_rl" type="continuous">
    <parent link="beam_left"/>
    <child link="wheel_rl"/>
    <origin xyz="${-beam_length/2} ${wheel_width} ${-body_height - beam_height/2}"/>
    <axis xyz="0 1 0"/>
  </joint>
  <joint name="body_to_wheel_rr" type="continuous">
    <parent link="beam_right"/>
    <child link="wheel_rr"/>
    <origin xyz="${-beam_length/2} ${-wheel_width} ${-body_height - beam_height/2}"/>
    <axis xyz="0 1 0"/>
  </joint>
  <joint name="body_to_wheel_fr" type="continuous">
    <parent link="body"/>
    <child link="wheel_fr"/>
    <origin xyz="0 ${-body_width/2 - wheel_width/2 - wheel_f_clear} ${-body_height/2}"/>
    <axis xyz="0 1 0"/>
  </joint>
</robot>
